# Generated by Django 3.0.4 on 2020-04-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=100)),
                ('subdistrict', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rent_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouth_rate', models.IntegerField(default=0)),
                ('electric_rate', models.IntegerField(default=0)),
                ('water_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.House_address')),
                ('rent_rate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Rent_rate')),
            ],
        ),
    ]
